sudo: false
language: node_js
os:
  - linux
node_js:
  - "stable"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
env:
  - secure: M1VIF3lZGFc2/okQrJcz3wpsHE9ahJcg0PjEa8tetYkXYWvgdzlUUMPpcNAnIXq5T+YqkIxj4cv1OwLAPwPEYva2HR7f097nAyL4rjGVohwV0rlXsFiJaheoWIM7lbNHiAUZFzH9Kc+61+VZmcNSByBsamgwG9KNafIUSOHQerSreU2Uyhz37KWnqhZ+9CB/HeLw1J2dfxcauzKIwJoM63vwL//4mQjO7RXoGLQNpdEQb+NtBquXwG/LFTEaUdIwVb0nn4rP2oErT0GAuIVQ+G5/s9AUCjcVjkxO2e65QPyPcIDQ2VUte0GiyLS0Ub/4DKL/79OQskUNmWKimBqapkIYoytJEaAjXF8nzMqwc3xG4HeI+Osvu9ZbS8hAdCx5Gl5gJ3vaRWjMIjCcAj6A/FE2n6ZkehkQTOmLBw2y2jJq+G4/io2iTSbw/aFHe0HGr3ojLLlY2wadTeZZISL6dbHc2tDFBFrRYVWfNUXTvyD3Sl6z7ZRrYvxqtWmUFimULYJi1SpkFi/6mnPDgOXV/aCMehzL9z62Del02s2JPvRTJbD3a2XT0sRDroWFoHlVK9PkcohXtOvd4lv9IC1rw4bRjD4nqrX010XoheHK4ScPf6WVKSJsdrGLqjij5DRTqkoYmCzWMsZbdlMLS3irxtcNqBQzAGaObj0lShvMTxo=
after_success: npm run codeclimate
